Added logging of client exceptions
smpio/python-httpapiclient pull request #4
Opened 2019-04-01 13:13 UTC by tangochin

2019-04-01 13:23 UTC, zokalo commented on src/httpapiclient/base.py
> +            log.exception(exc, extra={'trace_id': trace_id})
какая задача? может сделать это на том уровне, где требуется лог, а не для всех клиентов? это очень много логов будет

2019-04-01 14:13 UTC, tangochin commented on src/httpapiclient/base.py
> +            log.exception(exc, extra={'trace_id': trace_id})
Задача сейчас в том, чтобы логировать trace_id в Sentry при ошибке на стороне SMP. Если беспокоит большое количество логов, то возможно стоит сделать фильтр через https://docs.python.org/3/library/logging.html#logging.Logger.addFilter ?

2019-04-01 16:09 UTC, zokalo requested changes

2019-04-01 16:09 UTC, zokalo commented on src/httpapiclient/base.py
> +            log.exception(exc, extra={'trace_id': trace_id})
trace_id если он есть и так попадает в sentry. Речь шла о том, чтобы поместить trace_id именно в тело ответа

2019-04-01 16:13 UTC, evikbook commented on src/httpapiclient/base.py
> +            log.exception(exc, extra={'trace_id': trace_id})
@tangochin raise err_class(level='http', code=code, status_text=response.reason, content=response.content, trace_id=response.headers.get('X-Trace-ID'))

2019-04-01 16:20 UTC, zokalo approved these changes

2019-04-01 16:21 UTC, zokalo commented
@nailgun может замержить

2019-04-10 13:28 UTC, nailgun requested changes
Заголовок `X-Trace-ID` специфичен для SMP, а этот репозиторий - мини-фреймворк для реализации апи клиентов к произвольным сервисам. Короче, этим изменениям место в https://github.com/smpio/python-smp

2019-12-10 13:20 UTC, closed without merging